- project:
    check:
      jobs:
        - ansible-test-network-integration-ios-python27
        - ansible-test-network-integration-ios-python35
        - ansible-test-network-integration-ios-python36
        - ansible-test-network-integration-ios-python37
        - ansible-tox-linters
    gate:
      jobs:
        - ansible-test-network-integration-ios-python27
        - ansible-test-network-integration-ios-python35
        - ansible-test-network-integration-ios-python36
        - ansible-test-network-integration-ios-python37
        - ansible-tox-linters
